# Generated by Django 6.1.1 on 2026-09-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('github', models.URLField(blank=True)),
                ('live_demo', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='projects/')),
            ],
        ),
    ]
